# LOCAL PATHS
DEVICE_BASE := device/archos/ac101box
DEVICE_VENDOR := vendor/archos/ac101box
KERNEL_SOURCE := kernel/archos/ac101box

# inherit from the proprietary version
-include $(DEVICE_VENDOR)/BoardConfigVendor.mk

# Include
TARGET_SPECIFIC_HEADER_PATH := $(DEVICE_BASE)/include

# Board
TARGET_BOARD_PLATFORM_GPU := mali-720mp2

TARGET_BOOTLOADER_BOARD_NAME := mt8163
TARGET_NO_BOOTLOADER := true

# ARCH
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := generic

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a15

# CPU
TARGET_CPU_SMP := true

#Kernel
TARGET_PREBUILT_KERNEL := $(DEVICE_BASE)/prebuilt/Image.gz-dtb
TARGET_KERNEL_ARCH := arm64
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --ramdisk_offset 0x03f88000 --second_offset 0x00f00000 --tags_offset 0x0df88000 --base 0x40078000
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 496M quiet slub_max_order=0 slub_debug=O
BOARD_KERNEL_CMDLINE += androidboot.selinux=permissive
BOARD_KERNEL_BASE := 40078000
BOARD_KERNEL_OFFSET := 00008000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_FLASH_BLOCK_SIZE := 131072

# MTK
BOARD_HAS_MTK_HARDWARE := true
MTK_HARDWARE := true

# Binder API version
TARGET_USES_64_BIT_BINDER := true

# Common Flags
TARGET_GLOBAL_CFLAGS += -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -DMTK_HARDWARE -mfpu=neon -mfloat-abi=softfp
COMMON_GLOBAL_CFLAGS += -DMTK_HARDWARE -DREFRESH_RATE=60
COMMON_GLOBAL_CFLAGS += -DAMAZON_LOG -DADD_LEGACY_ACQUIRE_BUFFER_SYMBOL
COMMON_GLOBAL_CFLAGS += -DNO_SECURE_DISCARD

# MTK Common stuff
TARGET_BOARD_PLATFORM := mt8163
BOARD_USES_MTK_AUDIO := true
BOARD_HAS_MTK_HARDWARE := true
MTK_HARDWARE := true
MTK_APPENDED_DTB_SUPPORT := yes
BOARD_USES_MTK_HARDWARE := true

# WLAN
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_WLAN_DEVICE := mt66xx
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_$(BOARD_WLAN_DEVICE)
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_$(BOARD_WLAN_DEVICE)
WIFI_DRIVER_FW_PATH_PARAM:="/dev/wmtWifi"
WIFI_DRIVER_FW_PATH_STA:=STA
WIFI_DRIVER_FW_PATH_AP:=AP
WIFI_DRIVER_FW_PATH_STA:=P2P

# Bootanimation
TARGET_BOOTANIMATION_MULTITHREAD_DECODE := true
TARGET_BOOTANIMATION_PRELOAD := true
TARGET_BOOTANIMATION_TEXTURE_CACHE := true

# Camera
USE_CAMERA_STUB := true

# Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_MTK := true
BOARD_BLUETOOTH_DOES_NOT_USE_RFKILL := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := $(DEVICE_BASE)/bluetooth

#Vold
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/platform/mt_usb/musb-hdrc.0.auto/gadget/lun%d/file

# Graphics
BOARD_EGL_CFG := $(DEVICE_BASE)/configs/egl.cfg
USE_OPENGL_RENDERER := true
TARGET_USES_C2D_COMPOSITION := true
TARGET_USES_OVERLAY := true
#TARGET_USES_ION := true
#TARGET_DISPLAY_USE_RETIRE_FENCE := true
TARGET_USES_OVERLAY := true
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
TARGET_RUNNING_WITHOUT_SYNC_FRAMEWORK := true
TARGET_FORCE_HWC_FOR_VIRTUAL_DISPLAYS := true
MAX_VIRTUAL_DISPLAY_DIMENSION := 1
MAX_EGL_CACHE_KEY_SIZE := 12*1024
MAX_EGL_CACHE_SIZE := 1024*1024
TARGET_FORCE_HWC_FOR_VIRTUAL_DISPLAYS := true

# VSYNC
#SF_VSYNC_EVENT_PHASE_OFFSET_NS := -8000000
#VSYNC_EVENT_PHASE_OFFSET_NS := -8000000
#PRESENT_TIME_OFFSET_FROM_VSYNC_NS := 0
MTK_HWC_SUPPORT := yes
MTK_HWC_VERSION := 1.4.1

# Bootanimation
TARGET_BOOTANIMATION_MULTITHREAD_DECODE := true
TARGET_BOOTANIMATION_PRELOAD := true
TARGET_BOOTANIMATION_TEXTURE_CACHE := true
TARGET_SCREEN_WIDTH := 800
TARGET_SCREEN_HEIGHT := 1280

# Filesystem
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2936012800
BOARD_CACHEIMAGE_PARTITION_SIZE := 444596224
BOARD_USERDATA_PARTITION_SIZE := 1107296256
BOARD_FLASH_BLOCK_SIZE := 131072
TARGET_USERIMAGES_USE_EXT4 := true

BOARD_HAVE_BLUETOOTH_MTK := true
BOARD_BLUETOOTH_DOES_NOT_USE_RFKILL := true

# Enable Minikin text layout engine (will be the default soon)
USE_MINIKIN := true

#Use dlmalloc instead of jemalloc for mallocs
MALLOC_SVELTE := true

# Shims
TARGET_LD_SHIM_LIBS := \
/system/bin/vold|libshim_vold.so \
/system/lib/libmedia_jni.so|libshim_media.so \
/system/lib64/libmedia_jni.so|libshim_media.so \
/system/lib/hw/audio.primary.mt8163.so|libshim_audio.so \
/system/lib64/hw/audio.primary.mt8163.so|libshim_audio.so

# SELinux
BOARD_SEPOLICY_DIRS := \
       $(DEVICE_BASE)/sepolicy

BLOCK_BASED_OTA := false
TARGET_OTA_ASSERT_DEVICE := ac101box

#TWRP COMMON
TARGET_RECOVERY_FSTAB := $(DEVICE_BASE)/recovery.fstab
BOARD_HAS_NO_SELECT_BUTTON := true
TW_CUSTOM_CPU_TEMP_PATH := /sys/devices/virtual/thermal/thermal_zone2/temp
DEVICE_RESOLUTION := 1200x1920

# MTK HEADERS
BOARD_CUSTOM_BOOTIMG_MK := device/archos/ac101box/mkbootimg.mk

# Build without sources
$(shell mkdir -p $(OUT)/obj/KERNEL_OBJ/usr)
